#!/usr/bin/env bash
# Configures /etc/hosts to redirect localhost to 127.0.0.2 and facebook.com to 8.8.8.8

hosts_content=$(cat /etc/hosts | sed 's/127.0.0.1/127.0.0.2/g')
echo "$hosts_content" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
